definitions:
  model.AllResourceResponse:
    properties:
      is_publish:
        type: boolean
      label:
        type: string
      name:
        type: string
      plan:
        items:
          $ref: '#/definitions/model.Plan'
        type: array
      thumbnail:
        type: string
    type: object
  model.CreateUserRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        minLength: 6
        type: string
      phone:
        type: string
      username:
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    - phone
    - username
    type: object
  model.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  model.GetDownloadResourceResponse:
    properties:
      download:
        type: string
      version:
        type: string
    type: object
  model.GetResourceByNamePatchNotes:
    properties:
      logs:
        items:
          type: string
        type: array
      version:
        type: string
    type: object
  model.GetResourceByNameResponse:
    properties:
      description:
        type: string
      document:
        type: string
      images:
        items:
          type: string
        type: array
      is_publish:
        type: boolean
      label:
        type: string
      name:
        type: string
      patch_notes:
        items:
          $ref: '#/definitions/model.GetResourceByNamePatchNotes'
        type: array
      plan:
        items:
          $ref: '#/definitions/model.Plan'
        type: array
      thumbnail:
        type: string
      video:
        type: string
    type: object
  model.Homepage:
    properties:
      description:
        items:
          type: string
        type: array
      resourceLabel:
        type: string
      resourceName:
        type: string
      title:
        type: string
    type: object
  model.LoginUserRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  model.LoginUserResponse:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/model.UserResponse'
    type: object
  model.PatchNote:
    properties:
      download:
        type: string
      logs:
        items:
          type: string
        type: array
      version:
        type: string
    type: object
  model.Plan:
    properties:
      name:
        type: string
      price:
        type: integer
    type: object
  model.Resource:
    properties:
      description:
        type: string
      document:
        type: string
      images:
        items:
          type: string
        type: array
      is_publish:
        type: boolean
      label:
        type: string
      name:
        type: string
      patch_notes:
        items:
          $ref: '#/definitions/model.PatchNote'
        type: array
      plan:
        items:
          $ref: '#/definitions/model.Plan'
        type: array
      thumbnail:
        type: string
      video:
        type: string
    type: object
  model.User:
    properties:
      email:
        type: string
      firstname:
        type: string
      is_admin:
        type: boolean
      last_reset:
        type: string
      lastname:
        type: string
      license:
        type: string
      password:
        type: string
      phone:
        type: string
      reset_time:
        type: integer
      resources:
        items:
          $ref: '#/definitions/model.UserResource'
        type: array
      secret_code:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
  model.UserResource:
    properties:
      dayLeft:
        type: integer
      downloadLink:
        type: string
      name:
        type: string
      status:
        type: string
    type: object
  model.UserResponse:
    properties:
      email:
        type: string
      firstName:
        type: string
      isAdmin:
        type: boolean
      lastName:
        type: string
      lastReset:
        type: string
      license:
        type: string
      phone:
        type: string
      resetTime:
        type: integer
      resources:
        items:
          $ref: '#/definitions/model.UserResource'
        type: array
      secretCode:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
info:
  contact:
    email: thanathip.suw@gmail.com
    name: Awayfromus Support
    url: https://discord.com/invite/spqAG3Ktkv
  description: The Awayfromus web API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://awayfromus.dev/terms
  title: Awayfromus API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login user
      operationId: LoginUser
      parameters:
      - description: User data to be logged in
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginUserResponse'
        "400":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "401":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Login user
      tags:
      - user
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Create user
      operationId: CreateUser
      parameters:
      - description: User data to be created
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Create user
      tags:
      - user
  /api/v1/homepage:
    get:
      description: Get homepage information
      operationId: GetHomepageInformation
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Homepage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get Homepage
      tags:
      - homepage
    patch:
      consumes:
      - application/json
      description: Update homepage information
      operationId: UpdateHomepageInformation
      parameters:
      - description: Homepage data to be updated
        in: body
        name: Homepage
        required: true
        schema:
          $ref: '#/definitions/model.Homepage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Homepage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Homepage
      tags:
      - homepage
  /api/v1/resources:
    get:
      description: Get all resource information
      operationId: GetResourcesInformation
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.AllResourceResponse'
            type: array
        "500":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get Resources
      tags:
      - resource
    patch:
      consumes:
      - application/json
      description: Update resource information
      operationId: UpdateResource
      parameters:
      - description: Resource data to be updated
        in: body
        name: Resource
        required: true
        schema:
          $ref: '#/definitions/model.Resource'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Resource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update resource
      tags:
      - resource
    post:
      consumes:
      - application/json
      description: Create a new resource
      operationId: CreateNewResource
      parameters:
      - description: Resource data to be created
        in: body
        name: Resource
        required: true
        schema:
          $ref: '#/definitions/model.Resource'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Resource'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create new resource
      tags:
      - resource
  /api/v1/resources/{resourceName}:
    get:
      description: Get resource information by resoure name
      operationId: GetResourceByName
      parameters:
      - description: Resource name that need to get information
        in: path
        name: resourceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetResourceByNameResponse'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get resource by name
      tags:
      - resource
  /api/v1/resources/admin/{resourceName}:
    get:
      description: Get resource information by resoure name and require admin
      operationId: GetResourceByNameAndRequiredAdmin
      parameters:
      - description: Resource name that need to get information
        in: path
        name: resourceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Resource'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get resource by name required admin
      tags:
      - resource
  /api/v1/resources/download/{resourceName}:
    get:
      description: Get download resource by resoure name
      operationId: GetDownloadResource
      parameters:
      - description: Resource name that need to get download
        in: path
        name: resourceName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.GetDownloadResourceResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get download resource
      tags:
      - resource
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
